import fs from "fs";

/**
 * This is the log function that will log out a message and write the message in the .apilog file.
 *
 * @param {string} content The content of the log.
 */

export const log = (content: string): void => {
  const updatedContent = `[${String(Date.now)}] ${content}\n`;

  console.log(updatedContent);

  try {
    fs.appendFileSync("./log/.apilog", updatedContent);
  } catch (err: unknown) {
    console.log(err);
  }
};

/**
 * This is the log function that will error log out a message and write the message in the .apilog file.
 *
 * @param {string} content The content of the error log.
 */

export const error = (content: string): void => {
  const updatedContent = `ERROR: [${String(Date.now)}] ${content}\n`;

  console.log(updatedContent);

  try {
    fs.appendFileSync("./log/.apilog", updatedContent);
  } catch (err: unknown) {
    console.log(err);
  }
};

/**
 * This is the intialize function that will initialize the log file.
 */

export const init = (): void => {
  console.log("Initializing debugger tools...");

  try {
    fs.writeFileSync(
      "./log/.apilog",
      "This is the Chill&chat api log file, please do not edit this file!\nLogs:\n"
    );
  } catch (err: unknown) {
    console.log(err);
  }

  console.log("Done.");
};

const debug: any = {
  log: log,
  error: error,
  init: init,
};

export default debug;
