GET http://localhost:3001/api/users/get/all http/1.1

###

POST http://localhost:8080/api/login?key=000 http/1.1
content-type: application/json

{
"username":"Alvin",
"password":"asd"
}

###

POST http://localhost:8080/api/signup?key=000 http/1.1
content-type: application/json

{
    "id":"8ff39508-c80b-4419-9646-0bdd5277817f",
    "username":"Alvin",
    "password":"8888",
    "blocked":false,
    "verified":true,
    "bot": false
}

###

POST http://localhost:8080/api/create-room?key=000 http/1.1
content-type: application/json

{
    "id":"123",
    "name":"Alvin",
   "users":["Alvin"],
   "passcode":"pp"
}

###

GET http://localhost:8080/api/get-rooms?key=000&user=Alvin http/1.1

###
POST http://localhost:8080/api/block_user?key=000 http/1.1
content-type: application/json

{
"user":"Alvin",
"blockStatus":false
}

###
GET http://localhost:8080/api/users/get/admin/ http/1.1

###

GET http://localhost:8080/api/users/get/admin/password1234 http/1.1

###

PUT http://localhost:8080/api/users/block http/1.1
content-type: application/json

{
    "user":"admin",
    "blockStatus":true
}

